import type { Registry } from './registry.js';
import type { ToolLicense } from './types.js';

export const PLATFORM_LICENSES: ToolLicense[] = [
  { name: 'NeoTools (eigener Code)', license: 'MIT', url: 'https://opensource.org/licenses/MIT' },
  { name: 'Astro', license: 'MIT', url: 'https://github.com/withastro/astro' },
  { name: 'Preact', license: 'MIT', url: 'https://github.com/preactjs/preact' },
  { name: 'Tailwind CSS', license: 'MIT', url: 'https://github.com/tailwindlabs/tailwindcss' },
  { name: 'Zod', license: 'MIT', url: 'https://github.com/colinhacks/zod' },
  { name: 'Comlink', license: 'Apache-2.0', url: 'https://github.com/GoogleChromeLabs/comlink' },
  { name: 'fflate', license: 'MIT', url: 'https://github.com/101arrowz/fflate' },
  { name: 'qpdf-wasm (@jspawn/qpdf-wasm)', license: 'Apache-2.0', url: 'https://github.com/jsscheller/qpdf-wasm' },
  { name: '@cantoo/pdf-lib', license: 'MIT', url: 'https://github.com/cantoo-scribe/pdf-lib' },
  { name: '@jsquash/jpeg', license: 'Apache-2.0', url: 'https://github.com/jamsinclair/jSquash' },
  { name: '@jsquash/png', license: 'Apache-2.0', url: 'https://github.com/jamsinclair/jSquash' },
  { name: 'Tesseract.js', license: 'Apache-2.0', url: 'https://github.com/naptha/tesseract.js' },
  { name: '@noble/hashes', license: 'MIT', url: 'https://github.com/paulmillr/noble-hashes' },
  { name: 'ONNX Runtime', license: 'MIT', url: 'https://github.com/microsoft/onnxruntime' },
  { name: 'Transformers.js', license: 'Apache-2.0', url: 'https://github.com/huggingface/transformers.js' },
  { name: 'pkijs', license: 'BSD-3-Clause', url: 'https://github.com/PeculiarVentures/PKI.js' },
  { name: 'asn1js', license: 'BSD-3-Clause', url: 'https://github.com/PeculiarVentures/ASN1.js' },
  { name: 'diff', license: 'BSD-3-Clause', url: 'https://github.com/kpdecker/jsdiff' },
  { name: 'node-forge', license: 'BSD-3-Clause', url: 'https://github.com/digitalbazaar/forge' },
  { name: 'qrcode', license: 'MIT', url: 'https://github.com/soldair/node-qrcode' },
  { name: 'zxing-wasm', license: 'Apache-2.0', url: 'https://github.com/Sec-ant/zxing-wasm' },
  { name: 'marked', license: 'MIT', url: 'https://github.com/markedjs/marked' },
  { name: 'DOMPurify', license: 'MIT', url: 'https://github.com/cure53/DOMPurify' },
  { name: 'sRGB.icc (icc-profiles-free)', license: 'Zlib', url: 'https://sources.debian.org/src/icc-profiles-free/' },
  { name: '@jsquash/webp', license: 'Apache-2.0', url: 'https://github.com/jamsinclair/jSquash' },
  { name: '@jsquash/avif', license: 'Apache-2.0', url: 'https://github.com/jamsinclair/jSquash' },
  { name: '@jsquash/jxl', license: 'Apache-2.0', url: 'https://github.com/jamsinclair/jSquash' },
  { name: '@jsquash/oxipng', license: 'Apache-2.0', url: 'https://github.com/jamsinclair/jSquash' },
  { name: 'gifuct-js', license: 'MIT', url: 'https://github.com/matt-way/gifuct-js' },
  { name: 'gifenc', license: 'MIT', url: 'https://github.com/mattdesl/gifenc' },
  { name: 'upng-js', license: 'MIT', url: 'https://github.com/photopea/UPNG.js' },
  { name: 'utif', license: 'MIT', url: 'https://github.com/photopea/UTIF.js' },
  { name: 'heic-decode', license: 'MIT', url: 'https://github.com/catdad-experiments/heic-decode' },
  { name: 'libheif-js (dynamic)', license: 'LGPL-3.0-or-later', url: 'https://github.com/catdad-experiments/libheif-js' },
  { name: 'opentype.js', license: 'MIT', url: 'https://github.com/opentypejs/opentype.js' },
  { name: 'Source Sans 3', license: 'OFL-1.1', url: 'https://github.com/adobe-fonts/source-sans' },
  { name: '@pdf-lib/fontkit', license: 'MIT', url: 'https://github.com/Hopding/fontkit' },
  {
    name: '@ffmpeg/ffmpeg (JS-Wrapper)',
    license: 'MIT',
    url: 'https://github.com/ffmpegwasm/ffmpeg.wasm',
  },
  {
    name: '@ffmpeg/core (WASM, temporär offizieller Build)',
    license: 'GPL-2.0-or-later (temporär, ersetzen durch LGPL-Build)',
    url: 'https://github.com/ffmpegwasm/ffmpeg.wasm',
  },
  {
    name: 'FFmpeg (Ziel-Build ohne x264/x265)',
    license: 'LGPL-2.1-or-later',
    url: 'https://ffmpeg.org/legal.html',
  },
  { name: 'mp4-muxer', license: 'MIT', url: 'https://github.com/Vanilagy/mp4-muxer' },
  { name: 'mp4box.js', license: 'BSD-3-Clause', url: 'https://github.com/gpac/mp4box.js' },
  { name: 'libass', license: 'ISC', url: 'https://github.com/libass/libass' },
  { name: 'libvpx', license: 'BSD-3-Clause', url: 'https://github.com/webmproject/libvpx' },
  { name: 'libopus', license: 'BSD-3-Clause', url: 'https://gitlab.xiph.org/xiph/opus' },
  { name: 'libvorbis', license: 'BSD-3-Clause', url: 'https://gitlab.xiph.org/xiph/vorbis' },
  { name: 'LAME (libmp3lame)', license: 'LGPL-2.0-or-later', url: 'https://lame.sourceforge.io/' },
  { name: '@noble/ed25519', license: 'MIT', url: 'https://github.com/paulmillr/noble-ed25519' },
  { name: 'Fastify', license: 'MIT', url: 'https://github.com/fastify/fastify' },
  { name: '@fastify/multipart', license: 'MIT', url: 'https://github.com/fastify/fastify-multipart' },
  { name: '@fastify/rate-limit', license: 'MIT', url: 'https://github.com/fastify/fastify-rate-limit' },
  { name: 'zod-to-json-schema', license: 'MIT', url: 'https://github.com/StefanTerdell/zod-to-json-schema' },
  { name: 'chokidar', license: 'MIT', url: 'https://github.com/paulmillr/chokidar' },
  { name: 'libarchive.js (dynamic)', license: 'MIT', url: 'https://github.com/nika-begiashvili/libarchivejs' },
  { name: '7z-wasm (dynamic, not bundled)', license: 'LGPL-2.1-or-later', url: 'https://github.com/use-strict/7z-wasm' },
  { name: '@zip.js/zip.js', license: 'BSD-3-Clause', url: 'https://github.com/gildas-lormeau/zip.js' },
  { name: 'KoSIT XRechnung rules (optional fetch)', license: 'Apache-2.0', url: 'https://github.com/itplr-kosit/xrechnung-schematron' },
  { name: 'SaxonJS (optional Schematron)', license: 'MPL-2.0', url: 'https://www.saxonica.com/saxon-js/index.xml' },
  { name: 'libxml2-wasm (optional XSD)', license: 'MIT', url: 'https://github.com/jameslan/libxml2-wasm' },
  { name: 'OpenAI Whisper weights', license: 'MIT', url: 'https://github.com/openai/whisper' },
  { name: 'Distil-Whisper', license: 'MIT', url: 'https://github.com/huggingface/distil-whisper' },
  { name: 'OPUS-MT (Helsinki-NLP)', license: 'Apache-2.0', url: 'https://github.com/Helsinki-NLP/Opus-MT' },
  { name: 'mpg123-decoder', license: 'MIT', url: 'https://github.com/eshaz/mpg123-decoder' },
  { name: 'ogg-opus-decoder', license: 'MIT', url: 'https://github.com/eshaz/ogg-opus-decoder' },
  { name: '@wasm-audio-decoders/flac', license: 'MIT', url: 'https://github.com/eshaz/wasm-audio-decoders' },
  { name: 'all-MiniLM-L6-v2', license: 'Apache-2.0', url: 'https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2' },
  { name: 'DistilBART-CNN', license: 'Apache-2.0', url: 'https://huggingface.co/sshleifer/distilbart-cnn-6-6' },
  { name: 'pyannote.audio segmentation-3.0', license: 'MIT', url: 'https://github.com/pyannote/pyannote-audio' },
  { name: 'SheetJS Community (xlsx 0.18.x)', license: 'Apache-2.0', url: 'https://github.com/SheetJS/sheetjs' },
  { name: 'mammoth', license: 'BSD-2-Clause', url: 'https://github.com/mwilliamson/mammoth.js' },
  { name: 'parse5', license: 'MIT', url: 'https://github.com/inikulin/parse5' },
  { name: 'Papa Parse', license: 'MIT', url: 'https://github.com/mholt/PapaParse' },
  { name: 'iconv-lite', license: 'MIT', url: 'https://github.com/ashtuchkin/iconv-lite' },
  { name: 'yaml', license: 'ISC', url: 'https://github.com/eemeli/yaml' },
  { name: 'fast-xml-parser', license: 'MIT', url: 'https://github.com/NaturalIntelligence/fast-xml-parser' },
  { name: 'highlight.js', license: 'BSD-3-Clause', url: 'https://github.com/highlightjs/highlight.js' },
  { name: 'fonteditor-core', license: 'MIT', url: 'https://github.com/ecomfe/fonteditor-core' },
  { name: 'wawoff2', license: 'MIT', url: 'https://github.com/fontello/wawoff2' },
  { name: 'KaTeX', license: 'MIT', url: 'https://github.com/KaTeX/KaTeX' },
  { name: 'bwip-js', license: 'MIT', url: 'https://github.com/metafloor/bwip-js' },
  { name: 'sql.js', license: 'MIT', url: 'https://github.com/sql-js/sql.js' },
  { name: 'Source Serif 4', license: 'OFL-1.1', url: 'https://github.com/adobe-fonts/source-serif' },
  { name: 'Source Code Pro', license: 'OFL-1.1', url: 'https://github.com/adobe-fonts/source-code-pro' },
];

export function collectLicenses(registry: Registry, extra: ToolLicense[] = PLATFORM_LICENSES): ToolLicense[] {
  const map = new Map<string, ToolLicense>();
  for (const item of extra) {
    map.set(`${item.name}|${item.license}`, item);
  }
  for (const tool of registry.list()) {
    for (const lic of tool.licenses) {
      map.set(`${lic.name}|${lic.license}`, lic);
    }
  }
  return [...map.values()].sort((a, b) => a.name.localeCompare(b.name));
}
