import type { ToolLicense } from '@neotools/engine';

export const SPEECH_LICENSES: ToolLicense[] = [
  { name: 'NeoTools tools-speech', license: 'MIT', url: 'https://opensource.org/licenses/MIT' },
  { name: 'Transformers.js', license: 'Apache-2.0', url: 'https://github.com/huggingface/transformers.js' },
  { name: 'ONNX Runtime', license: 'MIT', url: 'https://github.com/microsoft/onnxruntime' },
  { name: 'OpenAI Whisper weights', license: 'MIT', url: 'https://github.com/openai/whisper' },
  { name: 'Distil-Whisper', license: 'MIT', url: 'https://github.com/huggingface/distil-whisper' },
  { name: 'OPUS-MT (Helsinki-NLP)', license: 'Apache-2.0', url: 'https://github.com/Helsinki-NLP/Opus-MT' },
  { name: 'all-MiniLM-L6-v2', license: 'Apache-2.0', url: 'https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2' },
  { name: 'DistilBART-CNN', license: 'Apache-2.0', url: 'https://huggingface.co/sshleifer/distilbart-cnn-6-6' },
  { name: 'pyannote.audio segmentation-3.0', license: 'MIT', url: 'https://github.com/pyannote/pyannote-audio' },
  { name: 'mpg123-decoder', license: 'MIT', url: 'https://github.com/eshaz/mpg123-decoder' },
  { name: 'ogg-opus-decoder', license: 'MIT', url: 'https://github.com/eshaz/ogg-opus-decoder' },
  { name: '@wasm-audio-decoders/flac', license: 'MIT', url: 'https://github.com/eshaz/wasm-audio-decoders' },
  { name: 'Tesseract.js (via tools-pdf)', license: 'Apache-2.0', url: 'https://github.com/naptha/tesseract.js' },
  { name: 'Zod', license: 'MIT', url: 'https://github.com/colinhacks/zod' },
];

export const AUDIO_ACCEPT = [
  'audio/wav',
  'audio/x-wav',
  'audio/wave',
  'audio/mpeg',
  'audio/mp3',
  'audio/ogg',
  'audio/opus',
  'audio/flac',
  'audio/x-flac',
  'audio/mp4',
  'audio/aac',
  'audio/webm',
  'video/mp4',
  'video/webm',
  'video/quicktime',
  'video/x-matroska',
  '.wav',
  '.wave',
  '.pcm',
  '.mp3',
  '.ogg',
  '.opus',
  '.flac',
  '.m4a',
  '.mp4',
  '.m4v',
  '.mov',
  '.webm',
  '.mkv',
];

export const SUBTITLE_ACCEPT = [
  'application/x-subrip',
  'text/vtt',
  'text/plain',
  'application/json',
  'application/ttml+xml',
  'application/xml',
  '.srt',
  '.vtt',
  '.ass',
  '.ssa',
  '.sbv',
  '.ttml',
  '.xml',
  '.lrc',
  '.json',
  '.txt',
];

export const TRANSCRIPT_ACCEPT = [
  'application/json',
  'application/x-subrip',
  'text/vtt',
  'text/plain',
  '.json',
  '.srt',
  '.vtt',
  '.txt',
];
